package main

CL_COLOR_DEFAULT :: Color3{1.0, 0.3, 1.0}
GL_MAJOR_VERSION :: 3
GL_MINOR_VERSION :: 3

MAX_BUFFERED_LINES_2D :: 200
MAX_BUFFERED_UI_LINES_2D :: 200
RECTANGLE_2D_VERTICIES :: 6 * 8
TEXT_CHAR_VERTICIES :: 6 * 8
MAX_BUFFERED_UI_CHARACTERS :: 1000
MAX_BUFFERED_IMUI_RECTANGLES_2D :: 200
MAX_BUFFERED_IMUI_CHARACTERS :: 1000

FONT_ATLAS_PADDING_PX :: 4
FONT_BITMAP_SIZE_DEFAULT :: 128
